# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn install -DskipTests
      - run: mkdir staging && cp target/*.jar staging 
  
      #- uses: actions/upload-artifact@v3
       # with:
        #  name: Package
         # path: staging
          
 #     - name: download artifact
  #      run: download -n Package
        
      - name: Check out code
        uses: actions/checkout@v2    
        
      - name: Build image
        run: docker build -t khawla8/myapp .

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u khawlapeaqock/springboot-app $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/khawlapeaqock/springboot-app/spring-github   
          VERSION=1.0
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag spring-app-git $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
    
