# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn install -DskipTests
      - run: |
          mkdir staging && cp target/*.jar staging 
          ls staging
            
      #- uses: actions/upload-artifact@v3
       # with:
        #  name: Package
         # path: staging
          
 #     - name: download artifact
  #      run: download -n Package
  
 
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: khawlapeaqock
          password: ${{ secrets.GHCR_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: khawla8/spring-git
          
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          dockerfile: DockerFile
          context: DockerFile
          file: DockerFile
          push: true
          tags: latest
          labels: 1.0
          
      #- uses: actions/checkout@v2    
      #- name: Build the hello-docker Docker image
       # run: |
        # docker build . --file DockerFile --tag ghcr.io/spring-app/git:latest
         #docker push ghcr.io/spring-app/git:latest
        
        
        
        
        
        
        
        
        
        

     # - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
     #   run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u khawlapeaqock/springboot-app $ --password-stdin
        
      #- name: Build image
      #  registry: docker.io
       # run: docker build -t khawla8/myapp .
        
      #- name: Push image
       # run: |
        #  IMAGE_ID=ghcr.io/khawlapeaqock/springboot-app/spring-github   
         # VERSION=1.0
          #echo IMAGE_ID=$IMAGE_ID
          #echo VERSION=$VERSION
          #docker tag spring-app-git $IMAGE_ID:$VERSION
          #docker push $IMAGE_ID:$VERSION
    
